# -*- coding: utf-8 -*-
"""weeki.A108260016.高豪廷.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11ndylGgjicVVtwa8UtrHw9RLfz2tX46p
"""

name = input('請問貴姓大名?')
print('你好，', name)

y = int(input('請問年紀?'))
print('原來你', y,'歲')

w = float(input('請問體重?'))
print('體重為', w)

上衣 = int(input('請輸入上衣數量?'))
褲子 = int(input('請輸入褲子數量?'))
背心 = int(input('請輸入背心數量?'))

總金額 = 上衣*300 + 褲子*350 + 背心*400
print('訂購服裝的總金額為',總金額)

半徑 = float(input('請輸入半徑?'))
PI = 3.14159

圓周長 = 2 * PI * 半徑
圓面積 = 半徑 * 半徑 * PI

print('圓周長為', 圓周長,'圓面積為', 圓面積)

c = float(input('請輸入攝氏溫度?'))

f = c * 9 / 5 +32
print('華氏溫度', f)

money = int(input('請輸入本金?'))
interest = float(input('請輸入年利率(%)?'))

y1 = money * (1 + interest/100)
y2 = money * ((1 + interest/100) ** 2)
y3 = money * ((1 + interest/100) ** 3)

print('第一年本利和為', y1)
print('第二年本利和為', y2)
print('第三年本利和為', y3)

第一次期中考成績 = int(input('請輸入第一次期中考成績?'))
第二次期中考成績 = int(input('請輸入第二次期中考成績?'))
期末考成績 = int(input('請輸入期末考成績?'))

總分 = 第一次期中考成績 + 第二次期中考成績 + 期末考成績
平均 = (第一次期中考成績 + 第二次期中考成績 + 期末考成績)/3
print('總分為', 總分,'平均為', 平均)

尺 = int(input('請輸入幾尺?'))
print(尺,'尺')
吋 = int(input('請輸入幾吋?'))
print(吋,'吋')
f = (尺*12+吋)*2.54
print('轉換成',f,'公分')

